---
plugin: aws_ec2
# Populate inventory with instances in these regions
regions:
  - ap-southeast-2
filters:
  tag:Name: example
keyed_groups:
  - key: tags['Role'] # the Role tag can be 'master' or 'node'
    prefix: tag # prefix is 'tag_'

    # so the groups are tag_master and tag_node